name: greet-meetup

on: [push]

jobs:
  greet-meetup-folks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Reading number of guests
        id: guests
        uses: juliangruber/read-file-action@v1
        with:
          path: ./guests.txt
          
      - name: Greet the folks
        uses: ./.github/actions/greet-meetup-action
        with:
          guests: ${{ steps.guests.outputs.content }}
