name: greet-meetup

on: [push]

jobs:
  greet-meetup-folks:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v3
      - name: read-guests
        id: guests
        uses: juliangruber/read-file-action@v1
        with:
            path: ./guests.txt
      - name: greet-folks
        run: echo "Hey folks, great to see ${{ steps.guests.outputs.content }} people joining our fun!"
